from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional


# ─────────────────────────────────────────────────────────────
# Shared helpers
# ─────────────────────────────────────────────────────────────

def _metadata(chunk: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "tokens": chunk.get("tokens"),
        "section_title": chunk.get("section_title") or "",
        "section_path": chunk.get("section_path") or "",
        "section_level": chunk.get("section_level") or 0,
        "page_start": chunk.get("page_start"),
        "page_end": chunk.get("page_end"),
        "previous_chunk_id": chunk.get("previous_chunk_id") or "",
        "next_chunk_id": chunk.get("next_chunk_id") or "",
    }


def _record(chunk: Dict[str, Any], embedding: Optional[List[float]]) -> Dict[str, Any]:
    return {
        "id": chunk.get("id"),
        "text": chunk.get("text"),
        "values": embedding,
        "metadata": _metadata(chunk),
    }


def build_vector_records(
    chunks: List[Dict[str, Any]],
    embeddings: Optional[List[List[float]]] = None,
) -> List[Dict[str, Any]]:
    if embeddings is not None and len(embeddings) != len(chunks):
        raise ValueError("embeddings length must match chunks length")
    return [
        _record(chunk, embeddings[idx] if embeddings is not None else None)
        for idx, chunk in enumerate(chunks)
    ]


# ─────────────────────────────────────────────────────────────
# Pinecone
# ─────────────────────────────────────────────────────────────

def export_pinecone(
    chunks: List[Dict[str, Any]],
    embeddings: Optional[List[List[float]]] = None,
) -> List[Dict[str, Any]]:
    """Return Pinecone upsert-ready dicts (id, values, metadata)."""
    records = build_vector_records(chunks, embeddings=embeddings)
    return [{"id": r["id"], "values": r["values"], "metadata": r["metadata"]} for r in records]


# ─────────────────────────────────────────────────────────────
# Weaviate
# ─────────────────────────────────────────────────────────────

def export_weaviate(
    chunks: List[Dict[str, Any]],
    embeddings: Optional[List[List[float]]] = None,
) -> List[Dict[str, Any]]:
    """Return Weaviate v4 import-ready dicts."""
    records = build_vector_records(chunks, embeddings=embeddings)
    return [
        {
            "id": r["id"],
            "properties": {"text": r["text"], **r["metadata"]},
            "vector": r["values"],
        }
        for r in records
    ]


# ─────────────────────────────────────────────────────────────
# FAISS / local JSONL
# ─────────────────────────────────────────────────────────────

def export_faiss_jsonl(
    chunks: List[Dict[str, Any]],
    output_path: str,
    embeddings: Optional[List[List[float]]] = None,
) -> str:
    """Write JSONL file for FAISS and local vector workflows."""
    records = build_vector_records(chunks, embeddings=embeddings)
    target = Path(output_path)
    with target.open("w", encoding="utf-8") as f:
        for row in records:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
    return str(target)


# ─────────────────────────────────────────────────────────────
# ChromaDB
# ─────────────────────────────────────────────────────────────

def export_chroma(
    chunks: List[Dict[str, Any]],
    collection: Any,
    embeddings: Optional[List[List[float]]] = None,
) -> None:
    """
    Upsert DocuWeave chunks directly into a ChromaDB collection.

    Example::

        import chromadb
        from docuweave import parse

        client = chromadb.Client()
        col    = client.get_or_create_collection("my_docs")

        doc = parse("paper.pdf")
        doc.to_chunks()
        doc.to_chroma(col)          # embeddings auto-generated by Chroma
        # or
        doc.to_chroma(col, embeddings=my_vecs)   # supply your own
    """
    ids       = [c["id"] for c in chunks]
    documents = [c.get("text", "") for c in chunks]
    metadatas = [_metadata(c) for c in chunks]

    kwargs: Dict[str, Any] = {
        "ids": ids,
        "documents": documents,
        "metadatas": metadatas,
    }
    if embeddings is not None:
        if len(embeddings) != len(chunks):
            raise ValueError("embeddings length must match chunks length")
        kwargs["embeddings"] = embeddings

    collection.upsert(**kwargs)


# ─────────────────────────────────────────────────────────────
# Qdrant
# ─────────────────────────────────────────────────────────────

def export_qdrant(
    chunks: List[Dict[str, Any]],
    client: Any,
    collection_name: str,
    embeddings: List[List[float]],
) -> None:
    """
    Upsert DocuWeave chunks into a Qdrant collection.

    ``embeddings`` is required — Qdrant does not auto-embed.

    Example::

        from qdrant_client import QdrantClient
        from docuweave import parse

        qc  = QdrantClient(":memory:")
        doc = parse("paper.pdf")
        doc.to_chunks()
        vecs = my_embed_fn([c["text"] for c in doc.to_chunks()])
        doc.to_qdrant(qc, "my_collection", embeddings=vecs)
    """
    try:
        from qdrant_client.models import PointStruct
    except ImportError as e:
        raise ImportError(
            "qdrant_client is required for Qdrant export. "
            "Install it with: pip install qdrant-client"
        ) from e

    if len(embeddings) != len(chunks):
        raise ValueError("embeddings length must match chunks length")

    points = [
        PointStruct(
            id=idx,
            vector=embeddings[idx],
            payload={"text": chunks[idx].get("text", ""), **_metadata(chunks[idx])},
        )
        for idx in range(len(chunks))
    ]
    client.upsert(collection_name=collection_name, points=points)


# ─────────────────────────────────────────────────────────────
# Milvus / Zilliz
# ─────────────────────────────────────────────────────────────

def export_milvus(
    chunks: List[Dict[str, Any]],
    collection: Any,
    embeddings: List[List[float]],
) -> None:
    """
    Insert DocuWeave chunks into a Milvus / Zilliz collection.

    The target collection must already exist with fields matching
    the metadata schema (section_title, section_path, etc.).

    Example::

        from pymilvus import Collection
        from docuweave import parse

        col  = Collection("my_docs")
        doc  = parse("paper.pdf")
        doc.to_chunks()
        vecs = my_embed_fn([c["text"] for c in doc.to_chunks()])
        doc.to_milvus(col, embeddings=vecs)
    """
    if len(embeddings) != len(chunks):
        raise ValueError("embeddings length must match chunks length")

    data = [
        {
            "id": idx,
            "text": chunks[idx].get("text", ""),
            "vector": embeddings[idx],
            **_metadata(chunks[idx]),
        }
        for idx in range(len(chunks))
    ]
    collection.insert(data)
